# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '05FilteringOperators' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 05FilteringOperators
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxRelay'
end
